AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda - SSM secret sample 

Resources:
  GGCSecretLmb:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GGCSecretLmb
      CodeUri: gglcsecret-func/
      Handler: app.lambda_handler
      Runtime: python3.7
      AutoPublishAlias: prod
